`timescale 1ns / 1ps
//============================================================================
//  Macintosh IIvi - Verilator Simulation Wrapper
//
//  Adapted from MacIIvi.sv for simulation
//============================================================================

module emu
(
	input         clk_sys,
	input         reset,

	// PS2 keyboard/mouse
	input [10:0]  ps2_key,
	input [24:0]  ps2_mouse,

	// RTC timestamp
	input [32:0]  timestamp,

	// VGA output
	output [7:0]  VGA_R,
	output [7:0]  VGA_G,
	output [7:0]  VGA_B,
	output        VGA_HS,
	output        VGA_VS,
	output        VGA_HB,
	output        VGA_VB,
	output        CE_PIXEL,

	// Audio output
	output [15:0] AUDIO_L,
	output [15:0] AUDIO_R,

	// ROM/disk loading interface (ioctl)
	input         ioctl_download,
	input         ioctl_wr,
	input [24:0]  ioctl_addr,
	input [15:0]  ioctl_dout,
	input [7:0]   ioctl_index,
	output reg    ioctl_wait = 1'b0,

	// SCSI block device interface. Slots: 0,1 = disks (SCSI 0/1),
	// 2 = CD-ROM (SCSI 3; FPGA top uses hps_io slot 3 for it — the sim
	// block-device model has no PRAM slot so the CD sits at 2).
	output [31:0] sd_lba[3],
	output [2:0]  sd_rd,
	output [2:0]  sd_wr,
	input  [2:0]  sd_ack,
	input  [7:0]  sd_buff_addr,
	input  [15:0] sd_buff_dout,
	output [15:0] sd_buff_din[3],
	input         sd_buff_wr,
	input  [2:0]  img_mounted,
	input  [63:0] img_size,

	// CPU debug outputs
	output [31:0] debug_pc,
	output [15:0] debug_opcode,
	output        debug_fetch_valid,
	output [31:0] debug_data_addr,

	// RAM debug outputs
	output [25:0] debug_ram_addr,
	output [15:0] debug_ram_din,
	output [15:0] debug_ram_dout,
	output        debug_ram_we,
	output        debug_ram_oe,
	output  [1:0] debug_ram_ds,
	output        debug_selectRAM,
	output        debug_selectROM,

	// Peripheral debug outputs
	output        debug_selectVIA,
	output        debug_selectAriel,
	output        debug_selectPseudoVIA,
	output        debug_selectSCSI,
	output        debug_selectSCC,
	output        debug_selectIWM,
	output        debug_selectASC,
	output        debug_selectVRAM,
	output [31:0] debug_cpuAddr,
	output [15:0] debug_cpuDataIn,    // Data from CPU to peripherals
	output [15:0] debug_cpuDataOut,   // Data from peripherals to CPU
	output        debug_cpuRW,        // 1=read, 0=write
	output        debug_cpuBusControl,
	output        debug_cpu_as,       // _cpuAS (0 = address strobe asserted)
	output        debug_cpu_dtack,    // _cpuDTACK (0 = acknowledged)

	// Serial port (SCC Channel A)
	output        serial_txd,       // SCC Channel A TX output (for sim-side RX)
	input         serial_rxd,       // SCC Channel A RX input (from sim-side TX)

	// Machine configuration inputs
	input  [1:0]  cfg_cpuType,      // Unused, kept for sim_main.cpp compatibility
	input  [2:0]  cfg_memSize,      // --ram: 0=4MB 1=8MB 2=20MB 3=36MB 4=68MB
	input  [1:0]  cfg_sdramMod,     // --sdram-module: emulated module 1=32MB 2=64MB 3=128MB
	input         nmi_pulse         // --nmi-at-frame: pulse a Level-7 NMI (MacsBug test)
);

	localparam SCSI_DEVS = 2;

	// Configuration
	localparam [1:0] status_cpu = 2'b10;     // 68020
	// Mac LC always runs at C15M (~15.67 MHz) - use 16 MHz clock enables

	////////////////////   CLOCKS   ///////////////////

	// Clock generation (clk_sys is 32MHz from testbench)
	wire clk_mem = clk_sys;  // Use same clock for memory
	wire pll_locked = !reset;

	// Clock enables - generated by addrController_top
	wire clk8_en_p, clk8_en_n;
	// V8 SCSI_PCLK / SCC RTxC source — see rtl/v8_clocks.sv (plan_040526.md Step 5).
	wire scsi_pclk_en;
	v8_clocks v8_clocks_inst (
		.clk_sys     (clk_sys),
		.reset       (~n_reset),
		.scsi_pclk_en(scsi_pclk_en)
	);
	wire clk16_en_p, clk16_en_n;
	wire clk8;

	// Reset logic
	// NOTE: Do NOT include _cpuReset_o here! The RESET instruction drives
	// reset_n low to reset peripherals, but should NOT reset the CPU itself.
	// IMPORTANT: In simulation, wait for ROM download to complete before releasing reset
	reg n_reset = 0;
	reg n_reset_prev = 0;
	reg dio_download_prev = 0;
	always @(posedge clk_sys) begin
		reg [15:0] rst_cnt;

		if (clk8_en_p) begin
			n_reset_prev <= n_reset;
			dio_download_prev <= dio_download;

			// Debug: track when download completes
			if (dio_download_prev && !dio_download) begin
				$display("[F%0d] SIM: dio_download went LOW - ROM download complete", sim_frame_count);
			end

			if(~pll_locked || reset || dio_download) begin
				rst_cnt <= '1;
				n_reset <= 0;
			end
			else if(rst_cnt) begin
				rst_cnt <= rst_cnt - 1'd1;
				// Debug: show countdown at key points only
				if (rst_cnt == 16'h0001) begin
					$display("[F%0d] SIM: rst_cnt about to expire, n_reset will go high", sim_frame_count);
				end
			end
			else begin
				n_reset <= 1;
			end

			// Debug: track when n_reset changes
			if (n_reset != n_reset_prev) begin
				$display("[F%0d] SIM: *** n_reset changed to %b *** (rst_cnt=%04x)", sim_frame_count, n_reset, rst_cnt);
			end
		end
	end

	///////////////////////////////////////////////////

	wire v8_ce_pix;

	// Display source select: run with +mdc824 to route the CARD's scanout to
	// the sim display (built-in video stays the default). NOTE: this no
	// longer touches the monitor sense — montype 7 ("no display") WEDGES the
	// ROM in early POST (MAME-proven with :vasp:MONTYPE forced: F2400 loop
	// at $4084xxxx, zero slot traffic). Sense stays 6; the card becomes the
	// boot display the real-hardware way, via the PRAM main-display setting.
	reg disp_mdc824 = 1'b0;
	initial disp_mdc824 = ($test$plusargs("mdc824") != 0);

	assign CE_PIXEL  = disp_mdc824 ? mdc_ce_pixel : v8_ce_pix;

	// Video Output — built-in (V8-heritage) video or the mdc824 card.
	// Card vga_blank is a display-enable (1 = visible); sim wants
	// active-high blanking on HB/VB, so invert (lbmactwo sim pattern).
	assign VGA_R  = disp_mdc824 ? mdc_r : v8_vga_r;
	assign VGA_G  = disp_mdc824 ? mdc_g : v8_vga_g;
	assign VGA_B  = disp_mdc824 ? mdc_b : v8_vga_b;
	wire VGA_DE = disp_mdc824 ? mdc_blank : v8_de;
	assign VGA_VS = disp_mdc824 ? mdc_vs : v8_vsync;
	assign VGA_HS = disp_mdc824 ? mdc_hs : v8_hsync;
	assign VGA_HB = disp_mdc824 ? ~mdc_blank : v8_hblank;
	assign VGA_VB = disp_mdc824 ? ~mdc_blank : v8_vblank;

	// Frame counter for debug logging
	reg [31:0] sim_frame_count = 0;
	reg vs_prev = 0;
	always @(posedge clk_sys) begin
		vs_prev <= VGA_VS;
		if (VGA_VS && !vs_prev)  // Rising edge of vsync = new frame
			sim_frame_count <= sim_frame_count + 1;
	end

	// ASC samples drive AUDIO_L/R directly (Commit C). Legacy DMA gone.
	assign AUDIO_L = asc_sample_l;
	assign AUDIO_R = asc_sample_r;

	// Macintosh IIvi memory configuration — VASP model: one contiguous block
	// at $0 (docs/VASP_RETARGET.md). Default (--ram absent) stays the 4MB base
	// config for the fastest RAM march during boot bring-up. Unlike MacIIvi.sv
	// there is deliberately NO sdram_sz clamp here: the sim runs any RAM size
	// against any emulated module (cfg_sdramMod -> sim_ram) so the oversized-
	// config corruption can be reproduced on purpose.
	wire [26:0] ram_size_bytes = (cfg_memSize == 3'd5) ? 27'h4400000 :  // 68MB
	                             (cfg_memSize == 3'd4) ? 27'h3000000 :  // 48MB
	                             (cfg_memSize == 3'd3) ? 27'h2400000 :  // 36MB
	                             (cfg_memSize == 3'd2) ? 27'h1400000 :  // 20MB
	                             (cfg_memSize == 3'd1) ? 27'h0800000 :  // 8MB
	                                                     27'h0400000;   // 4MB

	// Serial Ports - connect SCC Channel A to sim via serial_txd/serial_rxd ports
	wire serialOut;              // SCC Channel A TX (driven by SCC)
	wire serialIn = serial_rxd;  // SCC Channel A RX (driven by sim)
	wire serialCTS = 1'b0;
	wire serialRTS;
	assign serial_txd = serialOut;

	// V8 Video system wires
	wire v8_hsync, v8_vsync, v8_hblank, v8_vblank, v8_de;
	wire [7:0] v8_vga_r, v8_vga_g, v8_vga_b;
	wire [7:0] ariel_pixel_addr;
	wire [23:0] ariel_palette_data;
	wire [7:0] ariel_reg_dout;
	wire selectVDAC;       // From address decoder (VASP-internal CLUT/DAC)
	wire selectPseudoVIA;  // From address decoder
	wire selectVRAM;       // From address decoder
	wire selectBoxID;      // $5FFFFFFC machine-ID longword
	wire selectSuperSlot;  // NuBus $C/$D/$E super-slot space
	wire selectSlot;       // NuBus $FC/$FD/$FE slot space
	wire [1:0] slotNum;    // 0=$C 1=$D 2=$E
	// NuBus slot $E (mdc824) — keep in sync with MacIIvi.sv
	wire [15:0] nubusDataOut;
	wire        nubusAck_n;
	wire        nubus_nmrq_n;
	wire [7:0] pseudovia_dout;
	wire pseudovia_irq;
	wire capslock;

	// interconnects
	// CPU
	wire _cpuReset, _cpuReset_o, _cpuUDS, _cpuLDS, _cpuRW, _cpuAS;
	wire _cpuVMA, _cpuVPA, _cpuDTACK;
	wire E_rising, E_falling;
	wire [2:0] _cpuIPL;       // final IPL to CPU (Level-7 NMI applied below)
	wire [2:0] _cpuIPL_dc;    // raw IPL from dataController (VIA1 / PseudoVIA / SCC)
	wire [2:0] cpuFC;
	wire [7:0] cpuAddrHi;
	wire [31:0] cpuAddr;
	assign cpuAddr[0] = 1'b0;
	wire [7:0]  cpuAddrFullHi = cpuAddr[31:24];
	wire [15:0] cpuDataOut;

	// RAM/ROM
	wire _romOE;
	wire _ramOE, _ramWE;
	wire _memoryUDS, _memoryLDS;
	wire dioBusControl;
	wire cpuBusControl;
	wire [25:0] memoryAddr;  // 26-bit SDRAM word address from address controller
	wire [15:0] memoryDataOut;
	wire memoryLatch;
	// peripherals
	wire vid_alt;
	wire memoryOverlayOn, selectSCSI, selectSCC, selectIWM, selectVIA, selectRAM, selectROM, selectUnmapped;
	wire selectSCSIDMA;   // SCSI pseudo-DMA window (DACK) from address decoder
	wire scsiDREQ;        // SCSI pseudo-DMA request → gates CPU DTACK on DMA cycles
	wire scsiIRQ;         // NCR5380 latched IRQ (level) → pseudo-VIA IFR bit 3
	wire [15:0] dataControllerDataOut;

	// floppy disk image interface
	wire dskReadAckInt;
	wire [21:0] dskReadAddrInt;
	wire dskReadAckExt;
	wire [21:0] dskReadAddrExt;

	// dtack generation for 16 MHz mode
	reg  dtack_en, mem_latch_d;
	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			dtack_en <= 0;
		end
		else begin
			// mem_latch_d = registered memoryLatch: high at busPhase 0, i.e. the
			// START of each busCycle. (cpuBusControl & mem_latch_d) therefore
			// strobes once at the start of EVERY cpu slot.
			mem_latch_d <= memoryLatch;
			if (_cpuAS) dtack_en <= 0;
			// VRAM is SDRAM-backed and reads via the same cpu-slot as RAM,
			// so it must take the slot-aligned DTACK path (a cpu-slot start),
			// NOT the immediate !ROM&!RAM peripheral path. Excluding selectVRAM
			// here stops DTACK asserting before the SDRAM cpu-slot commits the
			// read/write (was truncating longword writes / sampling stale data).
			// H1: this was `!cpuBusControl_d & cpuBusControl` (rising edge), which
			// gave each ISOLATED cpu slot one DTACK opportunity. With slot 00 now
			// also a cpu slot the three slots are contiguous (one rising edge per
			// round), so we strobe at each cpu-slot start instead — same busPhase-0
			// timing as the old edge, but for all 3 slots (3 acks/round = +50%).
			if (!_cpuAS & ((cpuBusControl & mem_latch_d) | (!selectROM & !selectRAM & !selectVRAM))) dtack_en <= 1;
		end
	end

`ifdef PMMU_TRACE
	// DTACK-side probe (pairs with the PMMU walker probe in tg68k.v). Counts, per
	// ~262k-cycle window, how often the dtack_en SET condition's terms are true,
	// to explain why a stalled walker read never gets DTACK. During the stall the
	// last windows show the frozen picture.
	reg [31:0] dbg_dcyc, c_aslow, c_slot, c_setcond, c_den, c_selram;
	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			dbg_dcyc<=0; c_aslow<=0; c_slot<=0; c_setcond<=0; c_den<=0; c_selram<=0;
		end else begin
			dbg_dcyc <= dbg_dcyc + 1'b1;
			if (!_cpuAS)                                     c_aslow   <= c_aslow + 1'b1;
			if (cpuBusControl && mem_latch_d)                c_slot    <= c_slot + 1'b1;
			if (!_cpuAS && cpuBusControl && mem_latch_d)     c_setcond <= c_setcond + 1'b1;
			if (dtack_en)                                    c_den     <= c_den + 1'b1;
			if (selectRAM)                                   c_selram  <= c_selram + 1'b1;
			if (dbg_dcyc[17:0] == 18'd0) begin
				$display("DTACK WIN cyc=%0d aslow=%0d slot=%0d setcond=%0d den=%0d selram=%0d cpuAddr=%h selROM=%b selVRAM=%b dtack=%b @%0t",
				         dbg_dcyc, c_aslow, c_slot, c_setcond, c_den, c_selram, cpuAddr, selectROM, selectVRAM, _cpuDTACK, $time);
				c_aslow<=0; c_slot<=0; c_setcond<=0; c_den<=0; c_selram<=0;
			end
		end
	end
`endif

	// FC=7 is the 68k CPU space. cpuAddr[19:16] is the CPU-space cycle-type field:
	//   $F = interrupt acknowledge  -> autovector via VPA (Mac autovectored IRQs)
	//   else ($0 breakpoint, $2 coprocessor, ...) = no responder -> bus error.
	wire        fc7_iack = (cpuFC == 3'b111) && (cpuAddr[19:16] == 4'hF);
	wire        fc7_berr = (cpuFC == 3'b111) && !fc7_iack;
	// VASP 32-bit regions — keep both tops identical (rationale in MacIIvi.sv):
	//   io_space  = $50xxxxxx VASP I/O -> VPA/E-clock (except SCSI pseudo-DMA)
	//   slot_space = NuBus slot/super-slot space; open-bus $FFFF until the
	//   arbiter+mdc824 integration replaces this.
	wire        io_space   = (cpuAddrFullHi == 8'h50);
	wire        slot_space = selectSuperSlot || selectSlot;
	assign      _cpuVPA = fc7_iack ? 1'b0 : ((fc7_berr || slot_space) ? 1'b1 : ~(!_cpuAS && io_space && !selectSCSIDMA));
	assign      _cpuDTACK = fc7_berr ? 1'b1 :
	                        (slot_space && !_cpuAS) ? nubusAck_n :
	                        selectSCSIDMA ? ~scsiDREQ :
	                        (~(!_cpuAS && !io_space) | !dtack_en);

	// Peripheral (VPA) read-data register — mirror of MacIIvi.sv periph_din_reg
	// (fit-stabilization for the deep SCSI-CSR read cone; ported from MacLC
	// 0c8844b). Functionally transparent: VPA reads latch at s_state 6, ≥5
	// clk_sys after select settle, absorbing the +1 register latency. Mirrored
	// here so the sim exercises the registered path rather than trusting that
	// transparency claim FPGA-only.
	wire vpa_periph_read = !fc7_iack && !fc7_berr && !slot_space && !_cpuAS &&
	                       io_space && !selectSCSIDMA;
	reg [15:0] periph_din_reg;
	always @(posedge clk_sys) periph_din_reg <= dataControllerDataOut;
	wire [15:0] cpu_din_muxed = slot_space      ? nubusDataOut :
	                            vpa_periph_read ? periph_din_reg :
	                                              dataControllerDataOut;

	// Programmer's switch / Level-7 NMI — mirror of MacIIvi.sv (there the trigger is
	// the "R5" OSD button status[5]; in sim it is the nmi_pulse input driven by
	// --nmi-at-frame). Verifies the level-7 autovector path our CPU+glue takes.
	reg        nmi_req   = 1'b0;
	reg        nmi_btn_d = 1'b0;
	reg [15:0] nmi_to    = 16'd0;
	always @(posedge clk_sys) begin
		nmi_btn_d <= nmi_pulse;
		if (nmi_pulse && !nmi_btn_d) begin
			nmi_req <= 1'b1;
			nmi_to  <= 16'hFFFF;
			$display("[F%0d] NMI: asserted (Level-7 requested)", sim_frame_count);
		end else if (nmi_req) begin
			if ((fc7_iack && cpuAddr[3:1] == 3'b111) || nmi_to == 16'd0) begin
				nmi_req <= 1'b0;
				$display("[F%0d] NMI: cleared (%s)", sim_frame_count,
					(fc7_iack && cpuAddr[3:1] == 3'b111) ? "level-7 IACK TAKEN" : "timeout");
			end else
				nmi_to <= nmi_to - 1'b1;
		end
	end
	assign _cpuIPL = nmi_req ? 3'b000 : _cpuIPL_dc;

	wire        cpu_en_p      = clk16_en_p;
	wire        cpu_en_n      = clk16_en_n;
	assign      _cpuReset_o   = tg68_reset_n;

	// RESET-instruction soft peripheral reset (2026-08-08, ported from the
	// MacLC release-warm-restart-fix branch): both guest restart flavors
	// execute RESET + jump with NO Egret reset, and on real hardware that
	// instruction drives the external reset line. Stretch the CPU's pulse
	// to 16 clk for via6522 + the TIP latch (dataController), the pseudovia
	// INTERRUPT state, the ASC, and the SWIM (the LC's decisive wedge: a
	// warm boot inheriting ISM mode spins forever in the ROM's ISM->IWM
	// switch-back poll). Deliberately NOT the system reset (see the reset
	// NOTE above) and NOT the NCR/SCC (their setup must survive the ROM's
	// own T+4s RESET; resetting them regressed cold boot on the LC).
	reg [3:0] softrst_cnt = 4'd0;
	always @(posedge clk_sys) begin
		if (!_cpuReset_o)           softrst_cnt <= 4'hF;
		else if (softrst_cnt != 0)  softrst_cnt <= softrst_cnt - 1'd1;
	end
	wire soft_periph_rst = (softrst_cnt != 0);
	assign      _cpuRW        = tg68_rw;
	assign      _cpuAS        = tg68_as_n;
	assign      _cpuUDS       = tg68_uds_n;
	assign      _cpuLDS       = tg68_lds_n;
	assign      E_falling     = tg68_E_falling;
	assign      E_rising      = tg68_E_rising;
	assign      _cpuVMA       = tg68_vma_n;
	assign      cpuFC[0]      = tg68_fc0;
	assign      cpuFC[1]      = tg68_fc1;
	assign      cpuFC[2]      = tg68_fc2;
	assign      cpuAddr[31:1] = tg68_a[31:1];
	assign      cpuDataOut    = tg68_dout;

	wire        tg68_rw;
	wire        tg68_as_n;
	wire        tg68_uds_n;
	wire        tg68_lds_n;
	wire        tg68_E_rising;
	wire        tg68_E_falling;
	wire        tg68_vma_n;
	wire        tg68_fc0;
	wire        tg68_fc1;
	wire        tg68_fc2;
	wire [15:0] tg68_dout;
	wire [31:0] tg68_a;
	wire        tg68_reset_n;
	wire        tg68_longword;   // 32-bit access flag — drives SCSI pseudo-DMA byte packing
	wire [1:0]  tg68_busstate;

	// BERR: autovector path only for now. Unmapped-BERR disabled — see
	// docs/plan_040526.md: enabling it regresses boot because the CPU
	// emits high-bit addresses ($50xxxxxx etc.) early in ROM execution.
	// Bus-error CPU-space (FC=7) accesses that are NOT interrupt acknowledges:
	// the boot ROM's hardware-presence probes (`moves` to CPU space) which a real
	// 68030 faults because nothing decodes the cycle.
	// Slot-space: ACK with $FFFF (NuBus open-bus, the LBMacTwo
	// empty-slot mechanism) — TG68 berr is not handler-recoverable for
	// normal cycles. Keep both tops identical (MacIIvi.sv has the rationale).
	// Pseudo-DMA stall timeout → BERR — mirror of MacIIvi.sv (rationale there).
	localparam SDMA_TIMEOUT = 23'd8125000;  // ~250 ms @ 32.5 MHz
	reg [22:0] sdma_stall_ctr = 23'd0;
	reg        sdma_berr      = 1'b0;
	always @(posedge clk_sys) begin
		if (!_cpuReset) begin
			sdma_stall_ctr <= 0;
			sdma_berr      <= 0;
		end else if (_cpuAS) begin
			sdma_stall_ctr <= 0;
			sdma_berr      <= 0;
		end else if (selectSCSIDMA && !scsiDREQ && !sdma_berr) begin
			sdma_stall_ctr <= sdma_stall_ctr + 23'd1;
			if (sdma_stall_ctr == SDMA_TIMEOUT) begin
				sdma_berr <= 1'b1;   // held until AS deasserts
`ifdef SIMULATION
				$display("SDMA_BERR_TIMEOUT: addr=%h @%0t", cpuAddr, $time);
`endif
			end
		end else if (selectSCSIDMA)
			sdma_stall_ctr <= 0;
	end

	wire cpu_berr = (fc7_berr && !_cpuAS) || sdma_berr;
`ifdef SIMULATION
	reg _cpuAS_d;
	always @(posedge clk_sys) _cpuAS_d <= _cpuAS;
	always @(posedge clk_sys) begin
`ifdef VERBOSE_TRACE
		if (_cpuAS_d && !_cpuAS && cpuBusControl && selectUnmapped)
			$display("[F%0d] BERR_UNMAPPED: addr=%h fc=%b rw=%b", sim_frame_count, cpuAddr, cpuFC, _cpuRW);
		if (_cpuAS_d && !_cpuAS && |cpuAddrFullHi)
			$display("[F%0d] HIGH_ADDR: hi=%h addr=%h fc=%b rw=%b", sim_frame_count, cpuAddrFullHi, cpuAddr, cpuFC, _cpuRW);
`endif
	end
`endif

	tg68k tg68k (
		.clk        ( clk_sys      ),
		.reset      ( !_cpuReset ),
		.phi1       ( cpu_en_p  ),
		.phi2       ( cpu_en_n  ),
		.cpu        ( 2'b10 ),  // 68030 (Mac LC II); old selectable form: {status_cpu[1], |status_cpu}

		.dtack_n    ( _cpuDTACK  ),
		.rw_n       ( tg68_rw    ),
		.as_n       ( tg68_as_n  ),
		.uds_n      ( tg68_uds_n ),
		.lds_n      ( tg68_lds_n ),
		.fc         ( { tg68_fc2, tg68_fc1, tg68_fc0 } ),
		.reset_n    ( tg68_reset_n ),

		.E          (  ),
		.E_div      ( 1'b1 ),
		.E_PosClkEn ( tg68_E_falling ),
		.E_NegClkEn ( tg68_E_rising  ),
		.vma_n      ( tg68_vma_n ),
		.vpa_n      ( _cpuVPA ),

		.br_n       ( 1'b1    ),
		.bg_n       (  ),
		.bgack_n    ( 1'b1 ),

		.ipl        ( _cpuIPL ),
		.berr       ( cpu_berr ),
		.din        ( cpu_din_muxed ),
		.dout       ( tg68_dout ),
		.longword   ( tg68_longword ),
		.addr       ( tg68_a ),
		.busstate   ( tg68_busstate )
	);

	// CPU debug - capture PC and opcode during instruction fetch
	// busstate: 00 = fetch code, 10 = read data, 11 = write data, 01 = idle
	reg [31:0] last_fetch_pc;
	reg [15:0] last_fetch_opcode;
	reg        fetch_valid;
	reg        prev_as_n;
	reg [1:0]  prev_busstate;
	reg        as_falling_seen;
	reg [31:0] fetch_addr_latch;

	always @(posedge clk_sys) begin
		if (!n_reset) begin
			fetch_valid <= 0;
			prev_as_n <= 1;
			prev_busstate <= 2'b01;
			as_falling_seen <= 0;
			last_fetch_pc <= 0;
			last_fetch_opcode <= 0;
			fetch_addr_latch <= 0;
		end else begin
			// Default: clear fetch_valid after one cycle
			fetch_valid <= 0;

			// Track AS edges and busstate
			prev_as_n <= tg68_as_n;
			prev_busstate <= tg68_busstate;

			// Latch address when AS goes low during instruction fetch
			if (prev_as_n && !tg68_as_n && tg68_busstate == 2'b00) begin
				fetch_addr_latch <= tg68_a;
				as_falling_seen <= 1;
			end

			// Capture on AS rising edge (bus cycle complete) if this was a fetch
			if (!prev_as_n && tg68_as_n && as_falling_seen && prev_busstate == 2'b00) begin
				last_fetch_pc <= fetch_addr_latch;
				last_fetch_opcode <= dataControllerDataOut;
				fetch_valid <= 1;
				as_falling_seen <= 0;
			end

			// Clear if busstate changes away from fetch before completion
			if (tg68_busstate != 2'b00 && prev_busstate == 2'b00) begin
				as_falling_seen <= 0;
			end
		end
	end

	// Latch data address during non-fetch bus cycles (data read/write)
	reg [31:0] last_data_addr;
	always @(posedge clk_sys) begin
		if (!n_reset)
			last_data_addr <= 0;
		else if (prev_as_n && !tg68_as_n && tg68_busstate != 2'b00)
			last_data_addr <= tg68_a;
	end


	assign debug_pc = last_fetch_pc;
	assign debug_opcode = last_fetch_opcode;
	assign debug_fetch_valid = fetch_valid;
	assign debug_data_addr = last_data_addr;

	addrController_top ac0
	(
		.clk(clk_sys),
		.clk8(clk8),
		.clk8_en_p(clk8_en_p),
		.clk8_en_n(clk8_en_n),
		.clk16_en_p(clk16_en_p),
		.clk16_en_n(clk16_en_n),
		._cpuReset(_cpuReset),
		.cpuAddr(cpuAddr),
		._cpuUDS(_cpuUDS),
		._cpuLDS(_cpuLDS),
		._cpuRW(_cpuRW),
		._cpuAS(_cpuAS),
		.ram_size_bytes(ram_size_bytes),
		.memoryAddr(memoryAddr),
		.memoryLatch(memoryLatch),
		._memoryUDS(_memoryUDS),
		._memoryLDS(_memoryLDS),
		._romOE(_romOE),
		._ramOE(_ramOE),
		._ramWE(_ramWE),
		.dioBusControl(dioBusControl),
		.cpuBusControl(cpuBusControl),
		.selectSCSI(selectSCSI),
		.selectSCSIDMA(selectSCSIDMA),
		.selectSCC(selectSCC),
		.selectIWM(selectIWM),
		.selectASC(selectASC),
		.selectVIA(selectVIA),
		.selectRAM(selectRAM),
		.selectROM(selectROM),
		.selectVDAC(selectVDAC),
		.selectPseudoVIA(selectPseudoVIA),
		.selectVRAM(selectVRAM),
		.selectBoxID(selectBoxID),
		.selectSuperSlot(selectSuperSlot),
		.selectSlot(selectSlot),
		.slotNum(slotNum),
		.selectUnmapped(selectUnmapped),
		.words_per_line(v8_words_per_line),
		.vram_waddr(vram_bram_waddr),
		.vram_we(vram_bram_we),
		.memoryOverlayOn(memoryOverlayOn),
		.overlay_trigger_addr(),  // debug output, unused in sim


		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt)
	);

	wire [1:0] diskEject;
	wire [1:0] diskMotor, diskAct;

	// Video Mode Selection - from PVIA video_config register (bits 2:0 = bpp mode)
	wire [7:0] pvia_video_config;
	wire [7:0] asc_data_out;
	wire asc_irq;

	// Use actual video mode from pseudovia (ROM configures this via register 0x10)
	wire [2:0] v8_video_mode = pvia_video_config[2:0];

	// Monitor ID Selection - 640x480 VGA default (matches MacIIvi.sv and MAME's
	// VASP screen). Override with +montype=<n> to probe the sense-line behavior
	// — e.g. +montype=7 = "no onboard monitor connected" (standard Apple sense
	// code 7). NOTE: this is a STATIC sense, like MAME's montype<<3 and
	// pseudovia reg $10; it does NOT model the extended sense-line drive/read
	// dialogue the ROM performs when it sees sense 7. Investigating 2026-07-12
	// whether the ROM boots onto the NuBus card when onboard reports no monitor.
	reg [3:0] montype_ovr = 4'h6;
	initial if (!$value$plusargs("montype=%d", montype_ovr)) montype_ovr = 4'h6;
	wire [3:0] v8_monitor_id = montype_ovr;

	ariel_ramdac ariel(
		.clk_sys(clk_sys),
		.clk_pix(clk_sys),   // sim: single domain (FPGA: pixel clock)
		.reset(~n_reset),
		.reg_addr(cpuAddr[10:0]),
		.uds_n(_cpuUDS),
		.lds_n(_cpuLDS),
		.data_in(cpuDataOut[7:0]),
		.data_out(ariel_reg_dout),
		.we(selectVDAC && !_cpuRW && cpuBusControl),
		.req(selectVDAC && cpuBusControl),
		.mem_latch(memoryLatch),
		.cpu_as_n(_cpuAS),

		.pixel_index(ariel_pixel_addr),
		.rgb_out(ariel_palette_data),
		.ariel_written()  // Not used in sim
	);

	// Debug: disabled for now

	// Pseudovia register select is byte-granular and needs A0, which the 16-bit bus
	// drops (cpuAddr[0] is forced 0). Use the real A0 from the CPU (tg68_a[0]) for
	// the register LSB, matching MacIIvi.sv — without it odd registers alias onto
	// the even one below them.
	pseudovia pvia(
		.clk_sys(clk_sys),
		.reset(~n_reset),
		.soft_rst(soft_periph_rst),
		.addr({cpuAddr[12:1], tg68_a[0]}),
		.data_in(cpuDataOut[7:0]),
		.data_out(pseudovia_dout),
		.we(selectPseudoVIA && !_cpuRW && cpuBusControl),
		.req(selectPseudoVIA && cpuBusControl),
		.vblank_irq(v8_vblank),
		// NuBus slot IRQs: only slot $E is populated (mdc824 VBL, active low)
		.slot_irq_c(1'b0),
		.slot_irq_d(1'b0),
		.slot_irq_e(~nubus_nmrq_n),
		.asc_irq(asc_irq),
		// SCSI flags tied off (LC II lineage decision) — matches MacIIvi.sv;
		// revisit against MAME maciivx during disk bring-up.
		.scsi_irq(1'b0),
		.scsi_drq(1'b0),
		.irq_out(pseudovia_irq),
		.monitor_id(v8_monitor_id),
		.video_config(pvia_video_config)
	);

	// ------------------------------------------------------------------------
	// NuBus slot $E — Apple Display Card 8*24 (mdc824), bus-side integration.
	// Keep in sync with MacIIvi.sv (rationale there). Card VGA outputs are not
	// yet the sim display; onboard video remains on VGA_* for now.
	// ------------------------------------------------------------------------
	wire [15:0] nubusDataOut_card;
	wire        nubusAck_card;   // active low; 1 = card not responding
	wire [7:0]  mdc_r, mdc_g, mdc_b;
	wire        mdc_hs, mdc_vs, mdc_blank, mdc_ce_pixel;
	wire [24:0] mdc_vram_addr, mdc_vram_scan_addr;
	wire [15:0] mdc_vram_dout, mdc_vram_din, mdc_vram_scan_data;
	wire        mdc_vram_rd, mdc_vram_wr, mdc_vram_ready, mdc_vram_scan_rd;
	wire        card_ext_rd, card_ext_wr;
	wire [15:0] card_ext_din;
	wire        card_ext_ready;

	// Hybrid card VRAM (task #9, 2026-07-11): 384KB hot framebuffer in
	// BRAM (unchanged scanout) + cold tail to TOTAL_WORDS=1MB through the
	// ext_* port into the SDRAM window at word $100000. PrimaryInit
	// (decl-ROM code) sizes VRAM by writing $AAAAAAAA to byte offset
	// $F4B00 (~979KB) and reading it back (MAME rw-tap capture,
	// /tmp/mame_pinit_rw.txt); the IIvi ROM's Slot Manager — unlike the
	// Mac II's, which tolerates the miss (lbmactwo boots this card at
	// plain 384KB) — hard-fails the card on a miss: sResources dropped,
	// boot-display hunt dies smRecNotFnd, sad Mac $0F/$33. The tail
	// answers the probe; nothing is ever scanned out from it (8bpp @
	// 640x480 = 300KB fits BRAM). Matches MacIIvi.sv (keep in sync).
	nubus_video_mdc824 #(.SLOT_ID(4'hE), .VRAM_WORDS(157696),   // 308KB — keep in sync with MacIIvi.sv
	                     .TOTAL_WORDS(262144)) nubus_card (   // 512KB presented
		.clk(clk_sys),
		.reset(!_cpuReset),
		// Real A0 required (decl ROM = byte lane 3); see MacIIvi.sv note.
		.addr({cpuAddr[31:1], tg68_a[0]}),
		.data_in(cpuDataOut),
		.uds_lds({~_cpuUDS, ~_cpuLDS}),
		.cpu_longword(tg68_longword),
		.rw_n(_cpuRW),
		.cpu_as_n(_cpuAS),
		.select(selectSlot || selectSuperSlot),
		.data_out(nubusDataOut_card),
		.ack_n(nubusAck_card),
		.nmrq_n(nubus_nmrq_n),
		.vga_r(mdc_r), .vga_g(mdc_g), .vga_b(mdc_b),
		.vga_hs(mdc_hs), .vga_vs(mdc_vs), .vga_blank(mdc_blank),
		.vga_clk(),
		.vram_addr(mdc_vram_addr),
		.vram_dout(mdc_vram_dout),
		.vram_din(mdc_vram_din),
		.vram_rd(mdc_vram_rd),
		.vram_wr(mdc_vram_wr),
		.vram_ready(mdc_vram_ready),
		.ext_rd(card_ext_rd),
		.ext_wr(card_ext_wr),
		.ext_din(card_ext_din),
		.ext_ready(card_ext_ready),
		.vram_scan_addr(mdc_vram_scan_addr),
		.vram_scan_rd(mdc_vram_scan_rd),
		.vram_scan_data(mdc_vram_scan_data),
		.ioctl_wr(1'b0), .ioctl_addr(25'd0), .ioctl_data(16'd0),
		.ioctl_download(1'b0), .ioctl_index(8'd0),
		.overlay_en(1'b0),
		.monochrome(1'b0),
		.monitor_512(1'b0),   // sim: 640x480 13" profile
		.ce_pixel(mdc_ce_pixel),
		.dbg_video_en(), .dbg_vram_wr_cnt(), .dbg_vram_fetch_cnt(),
		.dbg_irq_cnt(), .dbg_ack_cnt(), .dbg_vblank_enable()
	);

	vram_ram #(.WORDS(157696)) mdc_vram (   // 308KB BRAM — must match VRAM_WORDS above
		.clk(clk_sys),
		.addr(mdc_vram_addr),
		.din(mdc_vram_dout),
		.dout(mdc_vram_din),
		.rd(mdc_vram_rd),
		.wr(mdc_vram_wr),
		.ready(mdc_vram_ready),
		.addr_b(mdc_vram_scan_addr),
		.rd_b(mdc_vram_scan_rd),
		.dout_b(mdc_vram_scan_data)
	);

	// ------------------------------------------------------------------------
	// NuBus slot $C — Apple Ethernet NB Twisted Pair (mirror of MacIIvi.sv —
	// keep both tops identical). Backing store is the behavioral sim_ddr3
	// model instead of the DDRAM port; with no "host" (MAGIC absent) the card
	// is invisible and slot space behaves exactly as before. +eth_magic /
	// +eth_rom=<hex> stage the window (scripts/gen_enetnbtp_rom.py --hex).
	// ------------------------------------------------------------------------
	wire        enet_card_sel, enet_card_ack, enet_irq;
	wire [15:0] enet_dout;
	wire [28:0] enet_mem_addr;
	wire  [7:0] enet_mem_burst, enet_mem_be;
	wire        enet_mem_rd, enet_mem_we;
	wire [63:0] enet_mem_wdata, enet_mem_rdata;
	wire        enet_mem_rvalid, enet_mem_busy;
	nubus_enetnbtp nubus_enet (
		.clk_sys   (clk_sys),
		.rst_core  (~pll_locked | reset),
		.rst_guest (~_cpuReset | ~_cpuReset_o),
		.ena_osd   (1'b1),
		.cpuAddr   (cpuAddr),
		.cpuDataIn (cpuDataOut),
		._cpuAS    (_cpuAS),
		._cpuUDS   (_cpuUDS),
		._cpuLDS   (_cpuLDS),
		._cpuRW    (_cpuRW),
		.card_sel  (enet_card_sel),
		.card_ack  (enet_card_ack),
		.card_dout (enet_dout),
		.irq       (enet_irq),
		.mem_addr  (enet_mem_addr),
		.mem_burst (enet_mem_burst),
		.mem_rd    (enet_mem_rd),
		.mem_we    (enet_mem_we),
		.mem_wdata (enet_mem_wdata),
		.mem_be    (enet_mem_be),
		.mem_rdata (enet_mem_rdata),
		.mem_rvalid(enet_mem_rvalid),
		.mem_busy  (enet_mem_busy)
	);
	sim_ddr3 sim_ddr3 (
		.clk   (clk_sys),
		.addr  (enet_mem_addr),
		.burst (enet_mem_burst),
		.rd    (enet_mem_rd),
		.we    (enet_mem_we),
		.wdata (enet_mem_wdata),
		.be    (enet_mem_be),
		.rdata (enet_mem_rdata),
		.rvalid(enet_mem_rvalid),
		.busy  (enet_mem_busy)
	);

	// Ethernet ahead of the mdc824 in the slot mux; a claimed cycle freezes
	// the open-bus timeout (DDR3-paced cycles can outlast 32 clk) — the
	// card's own ~4 ms watchdog bounds a dead-DDR3 stall instead.
	wire [15:0] nubusDataOut_mux = enet_card_sel ? enet_dout      : nubusDataOut_card;
	wire        nubusAck_mux     = enet_card_sel ? ~enet_card_ack : nubusAck_card;

	// Empty-slot open bus (slots $C/$D): 32 clk with no card ack -> $FFFF+DTACK.
	// (Was 4 clk — the card's cold-tail ext accesses ride the SDRAM cpu-slot
	// and ack in ~10-20 clk, which the old horizon would have eaten. Real
	// NuBus allows 25.6us; 32 clk ~= 1us keeps empty-slot probes snappy.)
	reg [5:0] nubus_timeout;
	always @(posedge clk_sys) begin
		if (_cpuAS) nubus_timeout <= 6'd0;
		else if (slot_space && nubusAck_mux && !enet_card_sel && !nubus_timeout[5])
			nubus_timeout <= nubus_timeout + 6'd1;
	end
	wire nubus_no_card = slot_space && nubusAck_mux && !enet_card_sel && nubus_timeout[5];
	assign nubusDataOut = nubus_no_card ? 16'hFFFF : nubusDataOut_mux;
	assign nubusAck_n   = nubus_no_card ? 1'b0    : nubusAck_mux;

`ifdef SIMULATION
	// [PROBE] peripheral read logger for the POST identity-check hunt
	// (2026-07-12): logs every VIA/VDAC/pseudoVIA/unmapped I/O READ with
	// the value the CPU received, frame-gated to keep the log sane. Same
	// latch-at-AS-low / report-at-AS-rise discipline as the NUBUS logger
	// below (selects are dead at AS-rise).
	reg        pr_as_d;
	reg        pr_cyc;
	reg [31:0] pr_addr;
	reg [15:0] pr_data;
	reg [3:0]  pr_kind;
	always @(posedge clk_sys) begin
		pr_as_d <= _cpuAS;
		if (!_cpuAS && _cpuRW &&
		    (selectVIA || selectVDAC || selectPseudoVIA || selectUnmapped) &&
		    sim_frame_count >= 32'd740 && sim_frame_count <= 32'd800) begin
			pr_cyc  <= 1'b1;
			pr_addr <= cpuAddr;
			pr_data <= dataControllerDataOut;
			pr_kind <= {selectUnmapped, selectPseudoVIA, selectVDAC, selectVIA};
		end
		if (!pr_as_d && _cpuAS && pr_cyc) begin
			pr_cyc <= 1'b0;
			$display("[PROBE] F%0d %s addr=%h data=%h", sim_frame_count,
			         pr_kind[0] ? "VIA " : pr_kind[1] ? "VDAC" :
			         pr_kind[2] ? "PVIA" : "UNMP", pr_addr, pr_data);
		end
	end

	// [NUBUS] access logger. The decoder's selects are combinational on
	// !_cpuAS, so they are ALREADY DEASSERTED at the AS-rise instant — the
	// original logger sampled slot_space there and could never fire (bug
	// found 2026-07-11 via the MAME slot-tap oracle: the F400 declaration
	// ROM probe was invisible). Latch the cycle's identity while AS is low;
	// report at AS-rise from the latches.
	reg        nb_as_d;
	reg        nb_cyc_slot, nb_cyc_open;
	reg [31:0] nb_cyc_addr;
	reg        nb_cyc_rw;
	reg [15:0] nb_cyc_data;
	integer nb_ack_cnt = 0, nb_open_cnt = 0;
	always @(posedge clk_sys) begin
		nb_as_d <= _cpuAS;
		if (!_cpuAS && slot_space) begin
			nb_cyc_slot <= 1'b1;
			nb_cyc_open <= nubus_no_card;
			nb_cyc_addr <= cpuAddr;
			nb_cyc_rw   <= _cpuRW;
			nb_cyc_data <= _cpuRW ? nubusDataOut : cpuDataOut;
		end
		if (!nb_as_d && _cpuAS && nb_cyc_slot) begin  // cycle ended
			nb_cyc_slot <= 1'b0;
			// Caps sized for the FULL Slot Manager declaration-ROM walk
			// (smRecNotFnd hunt 2026-07-11): the whole read stream, not a
			// first-contact teaser, so it can be diffed byte-by-byte against
			// the MAME slot-tap golden.
			if (nb_cyc_open) begin
				if (nb_open_cnt < 100) begin
					$display("[NUBUS] OPEN  addr=%h rw=%b -> FFFF", nb_cyc_addr, nb_cyc_rw);
					nb_open_cnt <= nb_open_cnt + 1;
				end
			end else begin
				if (nb_ack_cnt < 30000) begin
					$display("[NUBUS] CARD  addr=%h rw=%b data=%h", nb_cyc_addr, nb_cyc_rw, nb_cyc_data);
					nb_ack_cnt <= nb_ack_cnt + 1;
				end
			end
		end
	end
`endif

	// ASC sample outputs (Commit C will route to AUDIO_L/R)
	wire signed [15:0] asc_sample_l;
	wire signed [15:0] asc_sample_r;
	wire               asc_sample_tick;

	asc asc_inst(
		.clk(clk_sys),
		// soft_periph_rst: RESET instruction resets the ASC — keep in sync
		// with MacIIvi.sv (warm-restart fix).
		.reset(~n_reset || soft_periph_rst),
		.cs(selectASC),
		// cpuAddr[0] is forced 0; reconstruct the real A0 (tg68_a[0]) so the
		// odd ASC registers (MODE/FIFOMODE/CLOCK) don't alias onto the even reg
		// below them. Same fix as the SWIM/IWM instance above.
		.addr({cpuAddr[11:1], tg68_a[0]}),
		// Full 16-bit write bus: the FIFO must see BOTH byte lanes so MOVE.W/
		// MOVE.L fills land every sample (see the fifo_pend note in rtl/asc.sv).
		.data_in(cpuDataOut),
		.data_out(asc_data_out),
		.we(!_cpuRW && cpuBusControl),
		.cpu_as_n(_cpuAS),
		.uds_n(_cpuUDS),
		.lds_n(_cpuLDS),
		.sample_l(asc_sample_l),
		.sample_r(asc_sample_r),
		.sample_tick(asc_sample_tick),
		.irq(asc_irq)
	);

	// Historic 16.25 MHz pixel cadence: the sim keeps scanout on clk_sys with a
	// /2 advance enable (the FPGA now runs the module on a real per-monitor
	// pixel clock with pix_ce=1 — see rtl/pll_video.v / MacIIvi.sv). Keeping the
	// sim on the old grid preserves boot frame counts (screenshot @350 etc).
	reg sim_pix_ce = 1'b0;
	always @(posedge clk_sys) sim_pix_ce <= ~sim_pix_ce;

	maclc_v8_video v8_video(
		.clk_sys(clk_sys),
		.clk8_en_p(clk8_en_p),
		.pix_ce(sim_pix_ce),
		.reset(~n_reset),

		.video_mode(v8_video_mode),
		.monitor_id(v8_monitor_id),

		.hsync(v8_hsync),
		.vsync(v8_vsync),
		.hblank(v8_hblank),
		.vblank(v8_vblank),
		.vga_r(v8_vga_r),
		.vga_g(v8_vga_g),
		.vga_b(v8_vga_b),
		.de(v8_de),
		.ce_pix(v8_ce_pix),  // drives CE_PIXEL so the sim samples one pixel per real pixel-clock

		.palette_addr(ariel_pixel_addr),
		.palette_data(ariel_palette_data),

		.words_per_line(v8_words_per_line),
		.vram_raddr(v8_vram_raddr),
		.vram_rdata(v8_vram_rdata)
	);

	// On-chip framebuffer (BRAM). Video reads port B (Phase 2); CPU VRAM writes
	// are mirrored into port A. Single clk_sys domain => coherent. Must match MacIIvi.sv.
	wire [10:0] v8_words_per_line;
	wire [17:0] vram_bram_waddr;
	wire        vram_bram_we;
	wire [17:0] v8_vram_raddr;
	wire [15:0] v8_vram_rdata;

	vram_bram vram_fb(
		.a_clk(clk_sys),
		.b_clk(clk_sys),   // sim: single domain (FPGA: b_clk = pixel clock)
		.a_addr(vram_bram_waddr),
		.a_din(memoryDataOut),
		.a_be({~_cpuUDS, ~_cpuLDS}),
		.a_we(vram_bram_we),
		.a_dout(),                 // CPU reads still from SDRAM (dropped later)
		.b_addr(v8_vram_raddr),    // video scanline prefetch
		.b_dout(v8_vram_rdata)
	);

`ifdef SIMULATION
	// Phase 1 verification: confirm CPU VRAM writes are landing in the BRAM mirror.
	reg [31:0] vram_wr_count = 0;
	always @(posedge clk_sys) begin
		if (vram_bram_we) begin
			vram_wr_count <= vram_wr_count + 1;
			if (vram_wr_count < 5 || (vram_wr_count % 50000 == 0))
				$display("[F%0d] VRAM->BRAM write #%0d waddr=%05h data=%04h be=%b wpl=%0d",
					sim_frame_count, vram_wr_count, vram_bram_waddr, memoryDataOut,
					{~_cpuUDS,~_cpuLDS}, v8_words_per_line);
		end
	end

	// ---- CPU bus throughput / stall instrumentation (perf H1 measurement) ----
	// Per 60-frame window: how much of the time the CPU has a bus request
	// outstanding (_cpuAS low) but is STILL waiting for DTACK (_cpuDTACK high) =
	// slot-starved stall, vs how many SDRAM cpu transactions actually committed.
	reg [31:0] perf_clk = 0, perf_as = 0, perf_stall = 0, perf_commit = 0;
	reg [31:0] perf_last_frame = 0;
	always @(posedge clk_sys) begin
		perf_clk <= perf_clk + 1;
		if (!_cpuAS)              perf_as     <= perf_as + 1;
		if (!_cpuAS && _cpuDTACK) perf_stall  <= perf_stall + 1;
		if (cpuBusControl && memoryLatch && (selectRAM || selectVRAM || selectROM))
		                          perf_commit <= perf_commit + 1;
		if (sim_frame_count != perf_last_frame && (sim_frame_count % 60 == 0)) begin
			perf_last_frame <= sim_frame_count;
			$display("[F%0d] PERF: clk=%0d as=%0d stall=%0d (%0d%% of as) commits=%0d",
				sim_frame_count, perf_clk, perf_as, perf_stall,
				perf_as ? (perf_stall * 100 / perf_as) : 0, perf_commit);
			perf_clk <= 0; perf_as <= 0; perf_stall <= 0; perf_commit <= 0;
		end
	end
`endif

	// SCSI slot fan-out: disks drive array slots 0,1; the CD-ROM target drives
	// slot 2 (read-only — sd_wr[2] tied off). Mirrors the MacIIvi.sv stitching
	// so the shared dataController sees identical port shapes.
	wire [31:0] scsi_lba[2];
	wire [1:0]  scsi_rd, scsi_wr;
	wire [15:0] scsi_buff_din[2];
	wire [31:0] cd_lba;
	wire        cd_rd;
	wire [15:0] cd_buff_din;
	assign sd_lba[0] = scsi_lba[0];
	assign sd_lba[1] = scsi_lba[1];
	assign sd_lba[2] = cd_lba;
	assign sd_rd[1:0] = scsi_rd;
	assign sd_rd[2]   = cd_rd;
	assign sd_wr[1:0] = scsi_wr;
	assign sd_wr[2]   = 1'b0;
	assign sd_buff_din[0] = scsi_buff_din[0];
	assign sd_buff_din[1] = scsi_buff_din[1];
	assign sd_buff_din[2] = cd_buff_din;

	dataController_top #(SCSI_DEVS) dc0
	(
		.clk32(clk_sys),
		.clk8_en_p(clk8_en_p),
		.clk8_en_n(clk8_en_n),
		.scsi_pclk_en(scsi_pclk_en),
		.E_rising(E_rising),
		.E_falling(E_falling),
		._systemReset(n_reset),
		.softRst(soft_periph_rst),
		._cpuReset(_cpuReset),
		._cpuIPL(_cpuIPL_dc),
		.pseudovia_irq(pseudovia_irq),
		._cpuUDS(_cpuUDS),
		._cpuLDS(_cpuLDS),
		._cpuRW(_cpuRW),
		._cpuVMA(_cpuVMA),
		.cpuDataIn(cpuDataOut),
		.cpuDataOut(dataControllerDataOut),
		.cpuAddrRegHi(cpuAddr[12:9]),
		.cpuAddrRegMid(cpuAddr[6:4]),
		.cpuAddrRegLo(cpuAddr[2:1]),
		.cpuLongword(tg68_longword),
		.selectSCSI(selectSCSI),
		.selectSCSIDMA(selectSCSIDMA),
		.scsiDREQ(scsiDREQ),
		.scsiIRQ(scsiIRQ),
		// JTAG probe feeds — FPGA-only (dbg_probes.sv lives in MacIIvi.sv;
		// altsource_probe is an Altera primitive, never bring it into sim)
		.dbg_scsi(),
		.dbg_scsi2(),
		.dbg_scsi4(),
		.dbg_scsi5(),
		.dbg_ncr(),
		.dbg_ncr2(),
		.dbg_wr(),
		.selectSCC(selectSCC),
		.selectIWM(selectIWM),
		.selectVIA(selectVIA),
		.selectASC(selectASC),
		.asc_data_in(asc_data_out),
		.cpuBusControl(cpuBusControl),
		.memoryDataOut(memoryDataOut),
		.memoryDataIn(ram_do),
		.memoryLatch(memoryLatch),
		.selectVDAC(selectVDAC),
		.vdac_data_in(ariel_reg_dout),
		.selectPseudoVIA(selectPseudoVIA),
		.pseudovia_data_in(pseudovia_dout),
		.selectBoxID(selectBoxID),
		// sim boots as a Mac IIvi; flip to 1'b1 for Performa 600 identity
		// ($A55A2017) — CLI plumb can come later if A/B runs need it
		.machine_p600(1'b0),
		// was left unconnected in the LC II sim (floated 0) — the IIvi RAM
		// probe depends on unmapped reads returning open-bus $FFFF
		.selectUnmapped(selectUnmapped),

		.ps2_key(ps2_key),
		.capslock(capslock),
		.ps2_mouse(ps2_mouse),
		.serialIn(serialIn),
		.serialOut(serialOut),
		.serialCTS(serialCTS),
		.serialRTS(serialRTS),

		.timestamp(timestamp),

		._hblank(~v8_hblank),
		._vblank(~v8_vblank),
		.vid_alt(vid_alt),


		// Drive 2 tied off — mirror of MacIIvi.sv (single-SuperDrive machine)
		.insertDisk({1'b0, dsk_int_ins}),
		.diskSides({1'b0, dsk_int_ds}),
		.diskMFM({1'b0, dsk_int_mfm}),
		.diskHD({1'b0, dsk_int_hd}),
		.diskEject(diskEject),
		.dskReadAddrInt(dskReadAddrInt),
		.dskReadAckInt(dskReadAckInt),
		.dskReadAddrExt(dskReadAddrExt),
		.dskReadAckExt(dskReadAckExt),
		.diskMotor(diskMotor),
		.diskAct(diskAct),

		.img_mounted(img_mounted[1:0]),
		.img_size(img_size[40:9]),
		.io_lba(scsi_lba),
		.io_rd(scsi_rd),
		.io_wr(scsi_wr),
		.io_ack(sd_ack[1:0]),

		.sd_buff_addr(sd_buff_addr),
		.sd_buff_addr_hi(5'd0),   // sim HPS model serves 512-byte blocks only
		.sd_buff_dout(sd_buff_dout),
		.sd_buff_din(scsi_buff_din),
		.sd_buff_wr(sd_buff_wr),

		// CD-ROM target (SCSI ID 3) block interface — sim slot 2. cd_enable
		// tied on: the sim boot regression now exercises the disc-less CD
		// target during the ROM SCSI scan.
		.cd_enable(1'b1),
		.cd_img_mounted(img_mounted[2]),
		.cd_io_lba(cd_lba),
		.cd_io_rd(cd_rd),
		.cd_io_wr(),           // read-only target: never writes
		.cd_io_ack(sd_ack[2]),
		.cd_sd_buff_din(cd_buff_din),

		// dataController's CD-audio/Toolbox ports (cd_snd_l/r, tb_*, cdtb_*,
		// dbg_cda*) are intentionally left UNCONNECTED here: the headless sim
		// mixes no audio and has no Toolbox shared folder / CD-changer control
		// slot, so the tb_/cdtb_ inputs default to 0 (Toolbox + CD Changer
		// disabled) and the outputs dangle. Do NOT tie tb_mounted/tb_ack (or the
		// cdtb twins) to constants — Verilator 5.020 internal-faults on that
		// specific constant-to-input in this netlist; the unconnected form is
		// equivalent and is also what MacLC's sim.v does. (MacIIvi.sv wires them.)

		// PRAM persistence — tied off (step 1); FSM wired in step 2
		.pram_load_wr(1'b0),
		.pram_load_addr(8'd0),
		.pram_load_data(8'd0),
		.pram_save_addr(8'd0),
		.pram_save_data(),
		.pram_wr_stb(),
		.pram_ready(1'b1)
	);

	//////////////////////// DOWNLOADING ///////////////////////////

	wire dio_download = ioctl_download;
	wire [23:0] dio_addr = ioctl_addr[24:1];
	wire [7:0] dio_index = ioctl_index;
	// mirror of MacIIvi.sv: Main packs the matched extension into the upper
	// ioctl_index bits — compare only the MENU index (see MacIIvi.sv rationale)
	wire [5:0] dio_menu = dio_index[5:0];

	// Floppy disk image tracking (single drive — mirror of MacIIvi.sv)
	reg dsk_int_ds;
	reg dsk_int_ss;
	reg dsk_int_mfm;  // MFM-format image (ISM path): 720K or 1.44MB
	reg dsk_int_hd;   // 1.44MB HD (vs 720K DD)
	// DiskCopy 4.2 header skip — mirror of MacIIvi.sv (rationale there).
	reg dc42_name_ok;
	reg dc42_skip;
	reg [7:0] dc42_disk_format;    // DC42 byte 0x50: 0/1/2/3 = 400G/800G/720M/1440M
	// Disk-change presentation — mirror of MacIIvi.sv (full rationale there): a
	// swap must reach the guest as eject THEN insert, because it only learns
	// about media by polling CSTIN. The sim mounts one image and never swaps,
	// so this only delays that mount; it is here to keep the two tops from
	// diverging.
	localparam [25:0] DSK_EMPTY_CY = 26'h3FFFFFF;
	reg [25:0] dsk_int_empty_cy;
	wire dsk_int_empty = (dsk_int_empty_cy != DSK_EMPTY_CY);
	wire dsk_int_ins = !dsk_int_empty && (dsk_int_ds || dsk_int_ss || dsk_int_mfm);

	always @(posedge clk_sys) begin
		reg old_down;
		old_down <= dio_download;
		if(~old_down && dio_download && dio_menu == 6'd1) begin
			dsk_int_ds  <= 0;
			dsk_int_ss  <= 0;
			dsk_int_mfm <= 0;
			dsk_int_hd  <= 0;
			dsk_int_empty_cy <= 26'd0;
		end
		else if(dio_download && dio_menu == 6'd1)
			dsk_int_empty_cy <= 26'd0;
		else if(dsk_int_empty_cy != DSK_EMPTY_CY)
			dsk_int_empty_cy <= dsk_int_empty_cy + 26'd1;
		if(old_down && ~dio_download && dio_menu == 6'd1) begin
			dsk_int_ds <= (dio_addr == 409600) ||
			              (dc42_skip && (dio_addr == 409642 || dio_addr == 419242));
			dsk_int_ss <= (dio_addr == 204800) ||
			              (dc42_skip && (dio_addr == 204842 || dio_addr == 209642));
			dsk_int_mfm <= (dio_addr == 368640) || (dio_addr == 737280) ||
			               (dc42_skip && (dc42_disk_format == 8'd2 || dc42_disk_format == 8'd3));
			dsk_int_hd  <= (dio_addr == 737280) ||
			               (dc42_skip && dc42_disk_format == 8'd3);
			$display("SIM: floppy0 download end dio_addr(words)=%0d dc42=%b fmt=%02x -> ds=%b ss=%b mfm=%b hd=%b",
			         dio_addr, dc42_skip, dc42_disk_format,
			         (dio_addr == 409600) || (dc42_skip && (dio_addr == 409642 || dio_addr == 419242)),
			         (dio_addr == 204800) || (dc42_skip && (dio_addr == 204842 || dio_addr == 209642)),
			         (dio_addr == 368640) || (dio_addr == 737280) || (dc42_skip && (dc42_disk_format == 8'd2 || dc42_disk_format == 8'd3)),
			         (dio_addr == 737280) || (dc42_skip && dc42_disk_format == 8'd3));
		end
		if(diskEject[0]) begin
			dsk_int_ds <= 0;
			dsk_int_ss <= 0;
			dsk_int_mfm <= 0;
			dsk_int_hd <= 0;
		end
	end

	// (the dsk_ext_* mount block was removed with the second floppy —
	// mirror of MacIIvi.sv; diskEject[1] intentionally lands nowhere)

	// Download addresses (SDRAM word addresses, VASP layout):
	//   ROM (1MB): $000000 + offset
	//   Floppy:    $180000 + offset
	//   ($280000, the old Floppy-2 staging region, is unused since the
	//    second drive was dropped — index 2 can no longer arrive.)
	reg [25:0] dio_a;
	reg [15:0] dio_data;
	reg        dio_write;
	reg        dio_old_cyc = 0;

	// DC42 write offset: active from the word after the magic (word 41)
	wire [19:0] dio_flp_a = dc42_skip ? (dio_addr[19:0] - 20'd42) : dio_addr[19:0];

	always @(posedge clk_sys) begin
		if(ioctl_wr) begin
			if (dio_index[1:0] != 2'b00) begin
				// accept either byte lane order for the sim stream
				if (dio_addr[19:0] == 20'd0) begin
					dc42_skip    <= 1'b0;
					dc42_name_ok <= ((ioctl_dout[7:0]  >= 8'd1) && (ioctl_dout[7:0]  <= 8'd63)) ||
					                ((ioctl_dout[15:8] >= 8'd1) && (ioctl_dout[15:8] <= 8'd63));
				end else if (dio_addr[19:0] == 20'd40)
					dc42_disk_format <= ioctl_dout[7:0];  // byte 0x50 (low byte of word 40)
				else if (dio_addr[19:0] == 20'd41 && dc42_name_ok &&
				             (ioctl_dout == 16'h0001 || ioctl_dout == 16'h0100))
					dc42_skip <= 1'b1;
			end
			// Don't byte-swap for sim_ram (original swaps for SDRAM byte ordering)
			dio_data <= ioctl_dout;
			case (dio_index[1:0])
				2'b01:   dio_a <= 26'h0180000 + {6'b0, dio_flp_a};  // Floppy
				default: dio_a <= {7'b0, dio_addr[18:0]};           // ROM (1MB) at $000000 (must match addrController rom_sdram_word)
			endcase
			ioctl_wait <= 1;
		end

		dio_old_cyc <= dioBusControl;
		if(~dioBusControl) dio_write <= ioctl_wait;
		if(dio_old_cyc & ~dioBusControl & dio_write) ioctl_wait <= 0;
	end

	////////////////////////// RAM /////////////////////////////////

	// For simulation with synchronous RAM, use simplified direct download path
	wire download_cycle = dio_download && ioctl_wr;

	// SDRAM word address mapping (VASP layout — docs/VASP_RETARGET.md):
	// memoryAddr[25:0] is already the SDRAM word address from addrController.
	// Download path uses dio_a_comb directly.
	wire [25:0] dio_a_comb;
	assign dio_a_comb = (ioctl_index[1:0] == 2'b01) ? 26'h0180000 + {6'b0, ioctl_addr[20:1]} :  // Floppy
	                    {7'b0, ioctl_addr[19:1]};                                                 // ROM (1MB) at $000000 (must match addrController rom_sdram_word)

	// Card cold-tail (ext) SDRAM access — twin of MacIIvi.sv. The card's ext
	// port owns card words [196608, 524288) at SDRAM word $100000 + word
	// (= $130000..$17FFFF inside the reserved mdc824 window). An ext access
	// coincides with a CPU bus cycle TO the card, so the cpu RAM/ROM arms
	// are idle by construction; only floppy staging can collide, and then
	// the ext op just waits (the ready counter only advances on presented
	// cycles). Priority: download > floppy staging > card ext > cpu.
	wire [25:0] card_ext_addr = 26'h0100000 + {6'd0, mdc_vram_addr[19:0]};
	wire        card_ext_req  = card_ext_rd || card_ext_wr;
	wire        card_ext_slot = card_ext_req && !download_cycle
	                            && !dskReadAckInt && !dskReadAckExt;
	reg  [1:0]  card_ext_cnt = 2'd0;
	always @(posedge clk_sys) begin
		if (!card_ext_req)
			card_ext_cnt <= 2'd0;
		else if (card_ext_slot && card_ext_cnt != 2'd3)
			card_ext_cnt <= card_ext_cnt + 2'd1;
	end
	assign card_ext_ready = (card_ext_cnt == 2'd3);
	assign card_ext_din   = ram_do_raw;

	wire [25:0] ram_addr = download_cycle ? dio_a_comb :
	                       card_ext_slot  ? card_ext_addr : memoryAddr;

	// Use ioctl_dout directly for download (bypass registered dio_data)
	wire [15:0] ram_din  = download_cycle ? ioctl_dout :
	                       card_ext_slot  ? mdc_vram_dout : memoryDataOut;
	wire  [1:0] ram_ds   = download_cycle ? 2'b11 :
	                       card_ext_slot  ? 2'b11 : { !_memoryUDS, !_memoryLDS };
	// Use ioctl_wr directly as write enable during download (bypass registered dio_write)
	wire        ram_we   = download_cycle ? 1'b1 :
	                       card_ext_slot  ? card_ext_wr : !_ramWE;
	wire        ram_oe   = download_cycle ? 1'b0 :
	                       card_ext_slot  ? card_ext_rd :
	                       (!_ramOE || !_romOE || dskReadAckInt || dskReadAckExt);
	wire [15:0] ram_do_raw;
	// (LC II warm-vs-cold ROM patch retired — see MacIIvi.sv note / VASP_RETARGET.md.)
	wire [15:0] ram_do   = download_cycle ? 16'hffff : (dskReadAckInt || dskReadAckExt) ? extra_rom_data_demux : ram_do_raw;
	// Disk byte-parity select: must be dskReadAddr[0], NOT memoryAddr[0] (which
	// is dskReadAddr[1] after the >>1 word conversion drops bit 0). See the long
	// note at the matching demux in MacIIvi.sv — the old bit selected the wrong
	// byte on odd addresses and corrupted every floppy sector. Keep in sync.
	wire dsk_byte_odd = dskReadAckExt ? dskReadAddrExt[0] : dskReadAddrInt[0];
	wire [15:0] extra_rom_data_demux = dsk_byte_odd ?
						   {ram_do_raw[7:0],ram_do_raw[7:0]}:{ram_do_raw[15:8],ram_do_raw[15:8]};

	sim_ram ram
	(
		.clk            ( clk_sys     ),
		.reset          ( reset       ),
		.din            ( ram_din     ),
		.addr           ( ram_addr    ),
		.ds             ( ram_ds      ),
		.we             ( ram_we      ),
		.oe             ( ram_oe      ),
		.dout           ( ram_do_raw  ),
		.module_sz      ( cfg_sdramMod ),
		.frame_count    ( sim_frame_count )
	);

	// RAM debug outputs
	assign debug_ram_addr = ram_addr;
	assign debug_ram_din = ram_din;
	assign debug_ram_dout = ram_do_raw;
	assign debug_ram_we = ram_we;
	assign debug_ram_oe = ram_oe;
	assign debug_ram_ds = ram_ds;
	assign debug_selectRAM = selectRAM;
	assign debug_selectROM = selectROM;

	// Peripheral debug outputs
	assign debug_selectVIA = selectVIA;
	assign debug_selectAriel = selectVDAC;  // port name kept for sim_main.cpp compatibility
	assign debug_selectPseudoVIA = selectPseudoVIA;
	assign debug_selectSCSI = selectSCSI;
	assign debug_selectSCC = selectSCC;
	assign debug_selectIWM = selectIWM;
	assign debug_selectASC = selectASC;
	assign debug_selectVRAM = selectVRAM;
`ifdef SIMULATION
	// Track RAM test progress: log CPU data address during RAM writes
	// Samples periodically to avoid flooding output
	integer ram_wr_count = 0;
	reg [23:0] last_ram_wr_addr = 0;
	always @(posedge clk_sys) begin
		if (selectPseudoVIA && selectVRAM)
			$display("[F%0d] BUG: selectPseudoVIA AND selectVRAM both active! addr=%h", sim_frame_count, cpuAddr);
		if (selectPseudoVIA && !_cpuRW && cpuBusControl)
			$display("[F%0d] PVIA ACTIVE WRITE: cpuAddr=%h data=%h", sim_frame_count, cpuAddr, cpuDataOut);

		// Log RAM writes: first 10, then every 100000th
		if (!_ramWE && cpuBusControl) begin
			if (ram_wr_count < 10 || ram_wr_count % 100000 == 0) begin
				$display("[F%0d] RAM_WR[%0d]: cpuAddr=%h sdramAddr=%h data=%h PC=%h",
					sim_frame_count, ram_wr_count, cpuAddr, memoryAddr, cpuDataOut, last_fetch_pc);
			end
			last_ram_wr_addr <= cpuAddr;
			ram_wr_count <= ram_wr_count + 1;
		end

		// Log RAM reads: every 100000th
		if (!_ramOE && cpuBusControl) begin
			if (ram_wr_count > 0 && ram_wr_count % 100000 == 50000) begin
				$display("[F%0d] RAM_RD: cpuAddr=%h sdramAddr=%h PC=%h",
					sim_frame_count, cpuAddr, memoryAddr, last_fetch_pc);
			end
		end
	end

	// Runtime RAM-write watch: value-level visibility the instruction trace
	// lacks (it logs PCs + addresses but never data). Gated entirely by
	// plusargs so the build is reusable:
	//   ./Vemu ... +ramwatch_lo=<hex> +ramwatch_hi=<hex> +ramwatch_f0=<frame> +ramwatch_f1=<frame>
	// Added for the 2026-07-12 cursor-engine hang hunt (read the QuickDraw
	// frame slots / low-mem globals the endless fill consumes).
	reg [31:0] rw_lo = 32'h0, rw_hi = 32'h0;
	integer rw_f0 = 0, rw_f1 = 0;
	initial begin
		if ($value$plusargs("ramwatch_lo=%h", rw_lo)) ;
		if ($value$plusargs("ramwatch_hi=%h", rw_hi)) ;
		if ($value$plusargs("ramwatch_f0=%d", rw_f0)) ;
		if ($value$plusargs("ramwatch_f1=%d", rw_f1)) ;
	end
	always @(posedge clk_sys) begin
		if (rw_hi != 32'h0 && !_ramWE && cpuBusControl &&
		    cpuAddr >= rw_lo && cpuAddr <= rw_hi &&
		    sim_frame_count >= rw_f0 && sim_frame_count <= rw_f1)
			$display("[F%0d] RAMWATCH_WR: addr=%h data=%h PC=%h",
				sim_frame_count, cpuAddr, cpuDataOut, last_fetch_pc);
	end
`endif
	assign debug_cpuAddr = cpuAddr;
	assign debug_cpuDataIn = cpuDataOut;  // CPU writes this to peripherals
	assign debug_cpuDataOut = dataControllerDataOut;  // Peripherals send this to CPU
	assign debug_cpuRW = _cpuRW;  // 1=read, 0=write
	assign debug_cpuBusControl = cpuBusControl;
	assign debug_cpu_as = _cpuAS;
	assign debug_cpu_dtack = _cpuDTACK;

endmodule
