#!/bin/bash
#
# Convert the MacIIvi MC68030 TG68K core (integer kernel + PMMU + I/D cache,
# NO FPU) from VHDL to Verilog for Quartus + Verilator.
#
# Whole-design ghdl synth: elaborates TG68K (the top wrapper) with the FPU
# disabled and CPU="10" (68030), emitting a single TG68K.v that contains TG68K
# plus the tg68kdotc_kernel / tg68k_pmmu_030 / tg68k_cache_030 / tg68k_alu
# submodules. The Mac CPU wrapper instantiates the converted `TG68K` module.
#
# Notes:
#  - VHDL-2008 is required: TG68K.vhd associates an `out` formal with the
#    `buffer` port ADDR, which only the 2008 buffer rules permit.
#  - FPU_Enable=0 prunes the `if FPU_Enable=1 generate` FPU instance in the
#    kernel, so the TG68K_FPU*.vhd files are intentionally absent (the stock
#    Mac IIvi has no FPU; F-line instructions trap). A future IIvx mode can
#    re-import the FPU and flip these generics.
#  - Requires ghdl (validated with ghdl 6.0.0).
#
set -e
cd "$(dirname "${BASH_SOURCE[0]}")"

GHDL_FLAGS="--std=08 -fsynopsys -fexplicit -frelaxed"
TOP=TG68K
# NOTE: output is TG68K_030.v, NOT TG68K.v — on a case-insensitive filesystem
# (macOS) TG68K.v would collide with the legacy Mac wrapper tg68k.v. The module
# inside is still named TG68K.
OUT=TG68K_030.v
GENERICS="-gFPU_Enable=0 -gCPU=10"   # 68030, no FPU

# Dependency order: package -> ALU/PMMU/Cache leaves -> kernel -> top wrapper.
SRC="TG68K_Pack.vhd \
     TG68K_ALU.vhd \
     TG68K_PMMU_030.vhd \
     TG68K_Cache_030.vhd \
     TG68K_CacheCtrl_030.vhd \
     TG68KdotC_Kernel.vhd \
     TG68K.vhd"

command -v ghdl >/dev/null 2>&1 || { echo "Error: ghdl not found in PATH"; exit 1; }

echo "=== Step 1: Analyze VHDL (VHDL-2008) ==="
rm -f work-obj*.cf *.o
for f in $SRC; do echo "  -a $f"; ghdl -a $GHDL_FLAGS "$f"; done

echo "=== Step 2: Synthesize $TOP -> $OUT (FPU off, CPU=68030) ==="
ghdl synth $GHDL_FLAGS --latches $GENERICS --out=verilog "$TOP" > "$OUT"
echo "  wrote $OUT ($(wc -l < "$OUT") lines)"

echo "=== Step 3: Generate TG68K_verilog.qip ==="
{
  echo "# TG68K (MC68030 + PMMU + I/D cache, no FPU) Verilog QIP"
  echo "# Auto-generated by convert_to_verilog.sh from the VHDL sources in TG68K.qip"
  echo "set_global_assignment -name VERILOG_FILE [file join \$::quartus(qip_path) $OUT ]"
} > TG68K_verilog.qip

rm -f work-obj*.cf *.o
echo "=== Done. Top module: $TOP in $OUT (instantiate from the Mac CPU wrapper). ==="
